import { renderToStaticMarkup } from "react-dom/server";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { buildApplicationPacket } from "@/core/domain/applications/application-packet";

const mocks = vi.hoisted(() => ({
  applicationFindFirst: vi.fn(),
  candidateDocumentsFindMany: vi.fn(async () => []),
  notFound: vi.fn(() => {
    throw new Error("not found");
  }),
  writingFindFirst: vi.fn(),
}));

vi.mock("next/server", () => ({ connection: vi.fn(async () => undefined) }));
vi.mock("next/navigation", () => ({ notFound: mocks.notFound }));
vi.mock("@/features/accounts/require-workspace-page-actor", () => ({
  requireWorkspacePageActor: vi.fn(async () => ({ id: "candidate-1" })),
}));
vi.mock("@/integrations/auth/clerk-auth-provider", () => ({
  currentAuthProvider: vi.fn(() => ({})),
}));
vi.mock("@/lib/db/client", () => ({
  databaseClient: vi.fn(() => ({
    application: { findFirst: mocks.applicationFindFirst },
    applicationWritingArtifact: { findFirst: mocks.writingFindFirst },
    candidateDocument: { findMany: mocks.candidateDocumentsFindMany },
  })),
}));
vi.mock("./actions", () => ({
  confirmExternalApplicationAction: vi.fn(),
  generateCoverLetterAction: vi.fn(),
  markApplicationReadyAction: vi.fn(),
  refreshApplicationPacketAction: vi.fn(),
  saveApplicationOverridesAction: vi.fn(),
  selectApplicationResumeAction: vi.fn(),
  updateApplicationStateAction: vi.fn(),
}));

import ApplicationDetailPage from "./page";

const application = {
  answersSnapshot: {},
  createdAt: new Date("2026-09-06T10:00:00.000Z"),
  documentsSnapshot: [],
  events: [],
  externalConfirmedAt: null,
  externalSubmissionId: null,
  fitSnapshot: {},
  generatedTextSnapshot: {},
  id: "application-1",
  jobId: "job-1",
  job: {
    company: "Target Co",
    reviewQueueItems: [],
    title: "Python Engineer",
  },
  policyResultSnapshot: {},
  resumeVersion: null,
  state: "PREPARING",
  submissionDestination: null,
  submissionMechanism: "EXTERNAL_APPLICATION",
  submissionPayloadSnapshot: {},
  submittedAt: null,
  updatedAt: new Date("2026-09-06T11:00:00.000Z"),
};

const readyPacket = buildApplicationPacket({
  reviewed: true,
  source: {
    accountEmail: "candidate@example.test",
    profile: {
      firstName: "Avery",
      lastName: "Quill",
      applicationEmail: null,
      phone: null,
      location: null,
      countryCode: null,
      professionalTitle: "Python Engineer",
    },
    verifiedResumeFacts: [],
    experience: [],
    education: [],
    credentials: [],
    skills: [],
    languages: [],
    workAuthorization: null,
    sponsorshipRequired: null,
    answerMemories: [],
    selectedResume: {
      fileName: "resume.pdf",
      contentType: "application/pdf",
      storageKey: "candidate-documents/resume",
      tailored: false,
    },
    coverLetter: null,
    questions: [],
    questionInspection: "AVAILABLE",
    sourceName: "GREENHOUSE",
    targetRole: "Python Engineer",
  },
});

describe("application-detail cover letter workflow", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mocks.applicationFindFirst.mockResolvedValue(application);
    mocks.writingFindFirst.mockResolvedValue({
      content: "A grounded Python cover letter.",
      generatedAt: new Date("2026-09-06T12:00:00.000Z"),
      generator: "gemini-test-model",
    });
  });

  it("loads the latest owner-scoped draft and exposes explicit generation", async () => {
    const markup = renderToStaticMarkup(
      await ApplicationDetailPage({
        params: Promise.resolve({ applicationId: "application-1" }),
      }),
    );

    expect(mocks.applicationFindFirst).toHaveBeenCalledWith(
      expect.objectContaining({
        where: { id: "application-1", userId: "candidate-1" },
      }),
    );
    expect(mocks.writingFindFirst).toHaveBeenCalledWith({
      where: {
        targetJobId: "job-1",
        type: "COVER_LETTER",
        userId: "candidate-1",
      },
      orderBy: [{ generatedAt: "desc" }, { id: "desc" }],
      select: { content: true, generatedAt: true, generator: true },
    });
    expect(markup).toContain("A grounded Python cover letter.");
    expect(markup).toContain("Generated by gemini-test-model");
    expect(markup).toContain("Generate a new cover letter");
    expect(markup).toContain("Review required");
  });

  it("keeps a submitted draft visible but removes generation controls", async () => {
    mocks.applicationFindFirst.mockResolvedValue({
      ...application,
      state: "SUBMITTED",
      submittedAt: new Date("2026-09-06T13:00:00.000Z"),
    });

    const markup = renderToStaticMarkup(
      await ApplicationDetailPage({
        params: Promise.resolve({ applicationId: "application-1" }),
      }),
    );

    expect(markup).toContain("A grounded Python cover letter.");
    expect(markup).not.toContain("Generate a new cover letter");
    expect(mocks.candidateDocumentsFindMany).not.toHaveBeenCalled();
  });

  it("uses explicit employer-success attestation for a ready handoff", async () => {
    mocks.applicationFindFirst.mockResolvedValue({
      ...application,
      state: "READY",
      submissionDestination: "https://job-boards.greenhouse.io/acme/jobs/42",
      submissionPayloadSnapshot: { packet: readyPacket },
    });
    const markup = renderToStaticMarkup(
      await ApplicationDetailPage({
        params: Promise.resolve({ applicationId: "application-1" }),
      }),
    );
    expect(markup).toContain("Ready for employer handoff");
    expect(markup).toContain("click Submit yourself");
    expect(markup).toContain(
      "I submitted this application on the employer site and saw a success or confirmation result.",
    );
    expect(markup).toContain('name="confirmed"');
    expect(markup).toContain("required");
    expect(markup).toContain("Record candidate-confirmed submission");
    expect(markup).not.toContain("Confirm I submitted it");
  });

  it("labels candidate-confirmed completion without presenting an employer receipt", async () => {
    mocks.applicationFindFirst.mockResolvedValue({
      ...application,
      state: "SUBMITTED",
      submittedAt: new Date("2026-09-06T13:00:00.000Z"),
      externalConfirmedAt: new Date("2026-09-06T13:00:00.000Z"),
      externalSubmissionId: "external:application-1",
      events: [
        {
          id: "event-1",
          type: "SUBMISSION_CONFIRMED",
          fromState: "READY",
          toState: "SUBMITTED",
          createdAt: new Date("2026-09-06T13:00:00.000Z"),
          detail: { confirmation: "USER_CONFIRMED_EXTERNAL" },
        },
      ],
    });
    const markup = renderToStaticMarkup(
      await ApplicationDetailPage({
        params: Promise.resolve({ applicationId: "application-1" }),
      }),
    );
    expect(markup).toContain("Candidate-confirmed external submission");
    expect(markup).toContain("RoleProwl confirmation reference");
    expect(markup).toContain("not an employer receipt or ATS ID");
    expect(markup).toContain("Candidate confirmed external submission");
    expect(markup).not.toContain("External receipt");
  });
});
