"use client";

import { useActionState } from "react";
import {
  generateCoverLetterAction,
  type CoverLetterGenerationActionState,
} from "@/app/(app)/applications/[applicationId]/actions";

const initialState: CoverLetterGenerationActionState = {
  status: "idle",
  message: "",
};

export interface CoverLetterDraftView {
  readonly content: string;
  readonly generatedAt: string;
  readonly generator: string;
}

export function CoverLetterDraft({
  applicationId,
  canGenerate,
  draft,
}: {
  readonly applicationId: string;
  readonly canGenerate: boolean;
  readonly draft: CoverLetterDraftView | null;
}) {
  const [state, action, pending] = useActionState(
    generateCoverLetterAction,
    initialState,
  );

  return (
    <section className="card grid gap-3 border-brand p-5">
      <div className="grid gap-1">
        <p className="eyebrow">Candidate-controlled writing</p>
        <h2 className="text-base font-semibold">Cover letter draft</h2>
        <p className="m-0 text-sm">
          AI-generated draft · Review required. Generating a draft does not
          submit, send, or attach it to an employer application. Refresh the
          application packet separately if you choose to include it.
        </p>
      </div>

      {draft ? (
        <div className="grid gap-2">
          <p className="m-0 text-sm whitespace-pre-wrap">{draft.content}</p>
          <small className="text-foreground-muted">
            Generated by {draft.generator.slice(0, 100)} ·{" "}
            {new Date(draft.generatedAt).toISOString()}
          </small>
        </div>
      ) : (
        <p className="m-0 text-sm text-foreground-muted">
          No cover letter draft has been generated for this application.
        </p>
      )}

      {canGenerate && (
        <form action={action}>
          <input name="applicationId" type="hidden" value={applicationId} />
          <button
            className="button button-secondary"
            disabled={pending}
            type="submit"
          >
            {pending
              ? "Generating cover letter…"
              : draft
                ? "Generate a new cover letter"
                : "Generate cover letter"}
          </button>
        </form>
      )}

      <div aria-live="polite">
        {state.message ? (
          <p
            className={`m-0 text-sm ${
              state.status === "error" ? "text-danger" : "text-foreground-muted"
            }`}
          >
            {state.message}
          </p>
        ) : null}
      </div>
    </section>
  );
}
