import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { CoverLetterDraft } from "./cover-letter-draft";

describe("candidate-controlled cover letter draft", () => {
  it("shows the latest draft as review-only with an explicit regeneration action", () => {
    const markup = renderToStaticMarkup(
      createElement(CoverLetterDraft, {
        applicationId: "application-1",
        canGenerate: true,
        draft: {
          content: "A grounded, candidate-reviewed draft.",
          generatedAt: "2026-09-06T12:00:00.000Z",
          generator: "gemini-test-model",
        },
      }),
    );

    expect(markup).toContain("Cover letter draft");
    expect(markup).toContain("Review required");
    expect(markup).toContain("A grounded, candidate-reviewed draft.");
    expect(markup).toContain("Generated by gemini-test-model");
    expect(markup).toContain("Generate a new cover letter");
    expect(markup).toContain('name="applicationId"');
    expect(markup).toContain('value="application-1"');
    expect(markup).toContain("does not submit, send, or attach");
    expect(markup).not.toContain("Submit cover letter");
  });

  it("hides generation controls when the application is not eligible", () => {
    const markup = renderToStaticMarkup(
      createElement(CoverLetterDraft, {
        applicationId: "application-1",
        canGenerate: false,
        draft: {
          content: "Historical reviewed draft.",
          generatedAt: "2026-09-06T12:00:00.000Z",
          generator: "gemini-test-model",
        },
      }),
    );

    expect(markup).toContain("Historical reviewed draft.");
    expect(markup).not.toContain("Generate a new cover letter");
    expect(markup).not.toContain('name="applicationId"');
  });

  it("offers one explicit generation action when no draft exists", () => {
    const markup = renderToStaticMarkup(
      createElement(CoverLetterDraft, {
        applicationId: "application-1",
        canGenerate: true,
        draft: null,
      }),
    );

    expect(markup).toContain("No cover letter draft has been generated");
    expect(markup).toContain("Generate cover letter");
  });
});
